import { createFileRoute } from "@tanstack/react-router";
import { Search, SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { RestaurantCard } from "@/components/cenfud/restaurant-card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { categories, foodItems, restaurants } from "@/lib/cenfud-data";

export const Route = createFileRoute("/restaurants")({ validateSearch: (search: Record<string, unknown>) => ({ category: typeof search["category"] === "string" ? search["category"] : "" }), head: () => ({ meta: [{ title: "Restaurants near you — CenFud" }, { name: "description", content: "Browse and filter top-rated local restaurants on CenFud." }, { property: "og:title", content: "Restaurants near you — CenFud" }, { property: "og:description", content: "Browse local restaurants, cuisines, offers, ratings, and delivery times." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: RestaurantsPage });
function RestaurantsPage() { const initial = Route.useSearch().category; const [query, setQuery] = useState(initial); const [fastOnly, setFastOnly] = useState(false); const list = useMemo(() => restaurants.filter((item) => `${item.name} ${item.cuisine}`.toLowerCase().includes(query.toLowerCase()) && (!fastOnly || Number.parseInt(item.time) <= 25)), [query, fastOnly]); return <div className="mx-auto max-w-7xl px-4 pb-28 pt-10 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-xs font-black uppercase tracking-widest text-primary">Discover nearby</p><h1 className="mt-2 font-display text-4xl font-black sm:text-5xl">Restaurants for every craving</h1><p className="mt-3 text-muted-foreground">Fresh local favorites, honest delivery times, and offers worth opening the app for.</p></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={(e) => setQuery(e.target.value)} className="h-12 rounded-full pl-11" placeholder="Search restaurant or cuisine"/></div><Button variant={fastOnly ? "default" : "outline"} onClick={() => setFastOnly((value) => !value)} className="h-12 rounded-full px-5"><SlidersHorizontal/>Under 30 min</Button></div><div className="mt-6 flex gap-2 overflow-x-auto pb-2">{categories.map(([name, emoji]) => <Button key={name} variant={query === name ? "default" : "outline"} onClick={() => setQuery(query === name ? "" : name)} className="rounded-full"><span>{emoji}</span>{name}</Button>)}</div><div className="mt-8 flex items-center justify-between"><p className="font-bold">{list.length} restaurants</p><span className="text-sm text-muted-foreground">Recommended first</span></div><div className="mt-5 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{list.map((restaurant) => <RestaurantCard key={restaurant.id} restaurant={restaurant}/>)}</div>{list.length === 0 && <div className="py-24 text-center"><h2 className="font-display text-2xl font-bold">No restaurants found</h2><p className="mt-2 text-muted-foreground">Try another cuisine or clear your filters.</p><Button onClick={() => { setQuery(""); setFastOnly(false); }} className="mt-5 rounded-full">Clear filters</Button></div>}</div>; }
